version: "3.9"

services:
  app-news:
     build: ./
     ports:
        - "8080:8080"
     depends_on:
        - auth-keycloak-service
        - db-news
  db-news:
     image: postgres:16.1
     restart: always
     ports:
        - "5432:5432"
     environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=news
  auth-keycloak-service:
     image: quay.io/keycloak/keycloak:23.0
     restart: always
     command:
        - start-dev
        - --import-realm
        - --log-level=INFO
     volumes:
        - ./news-app/src/main/resources/keycloack/realm/news-realm.json:/opt/keycloak/data/import/news-realm.json
     ports:
        - "8090:8080"
     environment:
        - KC_HEALTH_ENABLED=true
        - KC_METRICS_ENABLED=true
        - KC_DB=postgres
        - KC_DB_URL=jdbc:postgresql://db-postgres-keycloak:5432/keycloak?useUnicode=true&characterEncoding=UTF-8
        - KC_DB_USERNAME=admin
        - KC_DB_PASSWORD=admin
        - KEYCLOAK_ADMIN=root
        - KEYCLOAK_ADMIN_PASSWORD=root
     depends_on:
        - db-postgres-keycloak
  db-postgres-keycloak:
     image: postgres:16.1
     restart: always
     ports:
     - "8091:5432"
     environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=keycloak
